todify/todo/urls.py
from django.urls import path

from .views import (
    task_create,
    task_update,
    task_delete,
    task_completed,
    task_completed_list,
    ordered_tasks_ajax,
)


app_name = 'todo'
urlpatterns = [
    path('create/', task_create, name='task-create'),
    path('<int:pk>/update/', task_update, name='task-update'),
    path('<int:pk>/delete/', task_delete, name='task-delete'),
    path('<int:pk>/completed/', task_completed, name='task-completed'),
    path('completed/', task_completed_list, name='task-completed-list'),
    path('ajax/order_tasks/', ordered_tasks_ajax, name='ajax-ordered-task'),
]

todify/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

from todify.todo.views import task_list


urlpatterns = [
    path('', task_list, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('todify.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('todo/', include('todify.todo.urls')),
]

urlpatterns += staticfiles_urlpatterns()

todify/todo/models.py
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from django.db import models


class Tag(models.Model):
    name = models.TextField(max_length=32, unique=True)
    slug = models.SlugField(unique=True)

    def _get_slug(self):
        return slugify(self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=128, blank=False)
    body = models.TextField(max_length=2048, blank=True)
    created_date = models.DateField(default=timezone.now)
    modified_date = models.DateField()
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='task_owner',
        on_delete=models.CASCADE
    )
    tags = models.ManyToManyField(Tag, blank=True)

    priority = models.PositiveIntegerField(default=9999)

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        # If task completed, sets the completion date
        if self.completed and self.completed_date is None:
            self.completed_date = timezone.now()

        if not self.id:
            self.created_date = timezone.now()
        self.modified_date = timezone.now()
        super().save(*args, **kwargs)

    def overdue_status(self):
        """ Return True if the task's time has expired """
        if self.due_date and timezone.now() > self.due_date:
            return True

    def get_absolute_url(self):
        return reverse('todo:task-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

todify/todo/forms.py
import datetime

from django.utils import timezone
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from .models import Task


class TaskForm(ModelForm):
    # due_date = forms.DateField(
    #     widget=forms.SelectDateWidget,
    #     label=_('Due date'),
    #     initial=datetime.date.today,
    #     help_text=_('Due date.')
    # )

    class Meta:
        model = Task
        fields = ['title', 'body']

todify/todo/views.py
from django.http import JsonResponse, Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string

from .models import Task
from .forms import TaskForm


def save_task_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            f = form.save(commit=False)
            f.owner = request.user
            f.save()
            data['form_is_valid'] = True
            if request.path.endswith('completed'):
                tasks = Task.objects.filter(owner=request.user).filter(completed=True).order_by('priority')
            else:
                tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
            data['html_task_list'] = render_to_string('todo/includes/partial_task_list.html', {
                'tasks': tasks
            })
        else:
            data['form_is_valid'] = False

    data['html_form'] = render_to_string(
        template_name,
        context={'form': form},
        request=request)
    return JsonResponse(data)


@login_required
def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
    else:
        form = TaskForm()
    return save_task_form(request, form, 'todo/includes/partial_task_create.html')


@login_required
def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
    else:
        form = TaskForm(instance=task)
    return save_task_form(request, form, 'todo/includes/partial_task_update.html')


@login_required
def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    data = dict()
    if request.method == 'POST':
        completed = task.completed
        task.delete()
        data['form_is_valid'] = True
        if completed:
            tasks = Task.objects.filter(owner=request.user).filter(completed=True).order_by('priority')
        else:
            tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
        data['html_task_list'] = render_to_string(
            'todo/includes/partial_task_list.html',
            {'tasks': tasks}
        )
    else:
        data['html_form'] = render_to_string(
            'todo/includes/partial_task_delete.html',
            context={'task': task},
            request=request,
        )
    return JsonResponse(data)


@login_required
def task_list(request):
    tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
    return render(request, 'todo/task_list.html', {'tasks': tasks})


@login_required
def task_completed_list(request):
    tasks = Task.objects.filter(owner=request.user).filter(completed=True).order_by('priority')
    return render(request, 'todo/task_list.html', {'tasks': tasks, 'completed': True})


@login_required
def task_completed(request, pk):
    task = get_object_or_404(Task, pk=pk)
    data = dict()
    if request.method == 'GET':
        task.completed = True
        task.save()
        tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
        data['html_task_list'] = render_to_string(
            'todo/includes/partial_task_list.html',
            {'tasks': tasks}
        )
    return JsonResponse(data)


@login_required
def ordered_tasks_ajax(request):
    if not request.is_ajax():
        return Http404

    tasks_id = request.GET.getlist('tasks[]')

    # Re-prioritize each task in list
    i = 1
    for task_id in tasks_id:
        task = Task.objects.get(pk=task_id)
        task.priority = i
        task.save()
        i += 1

    data = {'msg': 'OK'}
    return JsonResponse(data)

templates/todo/includes/partial_task_create.html
<form method="post" action="{% url 'todo:task-create' %}" class="js-task-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <div class="d-flex justify-content-between align-items-center w-100">
      <h4 class="modal-title">Create a new task</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  <div class="modal-body">
    {% include 'todo/includes/partial_task_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create task</button>
  </div>
</form>

templates/todo/includes/partial_task_delete.html
<form method="post" action="{% url 'todo:task-delete' task.pk %}" class="js-task-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <div class="d-flex justify-content-between align-items-center w-100">
      <h4 class="modal-title">Confirm task deletion</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the task — <strong class="font-weight-bold">{{ task.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete task</button>
  </div>
</form>

templates/todo/includes/partial_task_form.html
{{ form.non_field_errors }}
<div class="form-group">
  {{ form.title.errors }}
  <label for="{{ form.title.id_for_label }}">Task</label>
  <input class="form-control" type="text" name="title" maxlength="128" required="" id="id_title" placeholder="Task title"
  value="{% if form.title.value %}{{ form.title.value }}{% endif %}">
</div>
<div class="form-group">
  {{ form.body.errors }}
  <label for="{{ form.body.id_for_label }}">Description:</label>
  <textarea class="form-control" name="body" cols="40" rows="10" maxlength="2048" id="id_body">{% if form.body.value %}{{ form.body.value }}{% endif %}</textarea>
</div>

templates/todo/includes/partial_task_list.html
{% for task in tasks %}
  <div class="list-group shadow-sm" id="{{ task.pk }}">
    <a href="#" class="list-group-item list-group-item-action disable-link">
      <div class="d-flex justify-content-between align-items-center w-100">
        <h5 class="list-group-item-heading">{% if task.completed %}&#10004;{% else %}<button type="button" class="btn
        btn-outline-success btn-sm js-completed-task" data-url="{% url 'todo:task-completed' task.pk %}">Done</button>{% endif %} {{ task.title }}</h5>
        <div>
          <button type="button" class="btn btn-outline-warning btn-sm js-update-task" data-url="{% url 'todo:task-update' task.pk %}">Edit</button>
          <button type="button" class="btn btn-outline-danger btn-sm js-delete-task" data-url="{% url 'todo:task-delete' task.pk %}">Delete</button>
        </div>
      </div>
      <span class="d-block">{{ task.body }}</span>
    </a>
  </div>
{% empty %}
  <div class="media text-muted pt-3" draggable="false" ondragstart="false">
    <div class="media-body pb-3 mb-0 small lh-125">
      <div class="d-flex justify-content-between align-items-center w-100">
        <strong class="text-gray-dark">No tasks yet.</strong>
      </div>
    </div>
  </div>
{% endfor %}

templates/todo/includes/partial_task_update.html
<form method="post" action="{% url 'todo:task-update' form.instance.pk %}" class="js-task-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <div class="d-flex justify-content-between align-items-center w-100">
      <h4 class="modal-title">Update task</h4>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
  </div>
  <div class="modal-body">
    {% include 'todo/includes/partial_task_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update task</button>
  </div>
</form>