todify/todo/urls.py
from django.urls import path

from .views import (
    task_create,
    task_update,
    task_delete,
    task_completed,
    task_completed_list,
    ordered_tasks_ajax,
)


app_name = 'todo'
urlpatterns = [
    path('create/', task_create, name='task-create'),
    path('<int:pk>/update/', task_update, name='task-update'),
    path('<int:pk>/delete/', task_delete, name='task-delete'),
    path('<int:pk>/completed/', task_completed, name='task-completed'),
    path('completed/', task_completed_list, name='task-completed-list'),
    path('ajax/order_tasks/', ordered_tasks_ajax, name='ajax-ordered-task'),
]

todify/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

from todify.todo.views import task_list


urlpatterns = [
    path('', task_list, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('todify.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('todo/', include('todify.todo.urls')),
]

urlpatterns += staticfiles_urlpatterns()

todify/todo/models.py
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse
from django.db import models


class Tag(models.Model):
    name = models.TextField(max_length=32, unique=True)
    slug = models.SlugField(unique=True)

    def _get_slug(self):
        return slugify(self.name)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.CharField(max_length=128, blank=False)
    body = models.TextField(max_length=2048, blank=True)
    created_date = models.DateField(default=timezone.now)
    modified_date = models.DateField()
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='task_owner',
        on_delete=models.CASCADE
    )
    tags = models.ManyToManyField(Tag, blank=True)

    priority = models.PositiveIntegerField(default=9999)

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        # If task completed, sets the completion date
        if self.completed and self.completed_date is None:
            self.completed_date = timezone.now()

        if not self.id:
            self.created_date = timezone.now()
        self.modified_date = timezone.now()
        super().save(*args, **kwargs)

    def overdue_status(self):
        """ Return True if the task's time has expired """
        if self.due_date and timezone.now() > self.due_date:
            return True

    def get_absolute_url(self):
        return reverse('todo:task-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

todify/todo/forms.py
import datetime

from django.utils import timezone
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from .models import Task


class TaskForm(ModelForm):
    # due_date = forms.DateField(
    #     widget=forms.SelectDateWidget,
    #     label=_('Due date'),
    #     initial=datetime.date.today,
    #     help_text=_('Due date.')
    # )

    class Meta:
        model = Task
        fields = ['title', 'body']

todify/todo/views.py
from django.http import JsonResponse, Http404
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string

from .models import Task
from .forms import TaskForm


def save_task_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            f = form.save(commit=False)
            f.owner = request.user
            f.save()
            data['form_is_valid'] = True
            if request.path.endswith('completed'):
                tasks = Task.objects.filter(owner=request.user).filter(completed=True).order_by('priority')
            else:
                tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
            data['html_task_list'] = render_to_string('todo/includes/partial_task_list.html', {
                'tasks': tasks
            })
        else:
            data['form_is_valid'] = False

    data['html_form'] = render_to_string(
        template_name,
        context={'form': form},
        request=request)
    return JsonResponse(data)


@login_required
def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
    else:
        form = TaskForm()
    return save_task_form(request, form, 'todo/includes/partial_task_create.html')


@login_required
def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
    else:
        form = TaskForm(instance=task)
    return save_task_form(request, form, 'todo/includes/partial_task_update.html')


@login_required
def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    data = dict()
    if request.method == 'POST':
        completed = task.completed
        task.delete()
        data['form_is_valid'] = True
        if completed:
            tasks = Task.objects.filter(owner=request.user).filter(completed=True).order_by('priority')
        else:
            tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
        data['html_task_list'] = render_to_string(
            'todo/includes/partial_task_list.html',
            {'tasks': tasks}
        )
    else:
        data['html_form'] = render_to_string(
            'todo/includes/partial_task_delete.html',
            context={'task': task},
            request=request,
        )
    return JsonResponse(data)


@login_required
def task_list(request):
    tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
    return render(request, 'todo/task_list.html', {'tasks': tasks})


@login_required
def task_completed_list(request):
    tasks = Task.objects.filter(owner=request.user).filter(completed=True).order_by('priority')
    return render(request, 'todo/task_list.html', {'tasks': tasks, 'completed': True})


@login_required
def task_completed(request, pk):
    task = get_object_or_404(Task, pk=pk)
    data = dict()
    if request.method == 'GET':
        task.completed = True
        task.save()
        tasks = Task.objects.filter(owner=request.user).filter(completed=False).order_by('priority')
        data['html_task_list'] = render_to_string(
            'todo/includes/partial_task_list.html',
            {'tasks': tasks}
        )
    return JsonResponse(data)


@login_required
def ordered_tasks_ajax(request):
    if not request.is_ajax():
        return Http404

    tasks_id = request.GET.getlist('tasks[]')

    # Re-prioritize each task in list
    i = 1
    for task_id in tasks_id:
        task = Task.objects.get(pk=task_id)
        task.priority = i
        task.save()
        i += 1

    data = {'msg': 'OK'}
    return JsonResponse(data)

templates/todo/task_list.html
<!-- templates/todo/task_list.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Task list{% endblock %}
{% block link%}
  <link href="{% static 'css/task_list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <div class="container d-flex justify-content-between align-items-center w-100 border-bottom border-gray mb-3">
      {% if completed %}
        <h5>Completed tasks</h5>
      {% else %}
        <h5>Tasks</h5>
        <button type="button" class="btn btn btn-success mb-2 js-create-task" data-url="{% url 'todo:task-create' %}">Create task</button>
      {% endif %}

    </div>
    <div class="sortable" id="task-list">
      {% include 'todo/includes/partial_task_list.html' %}
    </div>
    {% if completed %}
      <small class="d-block text-right mt-3">
        <a href="{% url 'home' %}">View pending tasks</a>
      </small>
    {% else %}
      <small class="d-block text-right mt-3">
        <a href="{% url 'todo:task-completed-list' %}">View completed tasks</a>
      </small>
    {% endif %}
</div>

  <div class="modal fade" id="modal-task">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>

{% endblock %}
{% block script %}
  <script src="{% static '/js/tasks.js' %}"></script>
  <script>
    $( "#task-list" ).on("click", "button.task-delete", function () {
      let task = $(this).closest("button");
      $.ajax({
        url: task.attr("task-delete-url"),
        data: {"task_pk": task.attr("task-id")},
        dataType: 'json',
        success: function (data) {
          if (!data.error) {
            $("#" + task.attr("task-id")).slideUp("fast")
          }
        }
      });
    });

    function getIds(elements) {
      let ids = [];
      for (let i = 0; i < elements.length; i++) {
        ids.push(elements[i].id)
      }
      return ids
    }

    function send_order() {
      let elements = document.getElementsByClassName("list-group");
      let ids = getIds(elements);
      $.ajax({
        method: "GET",
        url: "/todo/ajax/order_tasks/",
        data: {"tasks": ids},
        dataType: 'json',
       });
    }

    $( function() {
      $( "div.sortable" ).sortable({
        update: function( event, ui ) {
          send_order();
        }
      });
      $( "div.sortable" ).disableSelection();
      $( "#task-list" ).on("click", "a.disable-link", function(e) {
        e.preventDefault();
        //do other stuff when a click happens
      });
    } );
  </script>
{% endblock %}